apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: backend-tests-go-baqzofmp
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/backend-tests-go-baqzofmp:28a40af8881cdef72f0799fec19e1630be579c39@sha256:ab0e44c30aed5a0ba826f4c802600d074aab078ffd341c6b6bae035520afe9a6
        name: container-image  
